"""Add worker role ratings table

Revision ID: a15092933abd
Revises: 025a00ce901a
Create Date: 2025-09-29 11:33:06.244850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15092933abd'
down_revision = '025a00ce901a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_role_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('job_role_id', sa.Integer(), nullable=False),
    sa.Column('difficulty_rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_role_rating')
    # ### end Alembic commands ###
