"""Add algorithm logs table

Revision ID: c42403d6f648
Revises: a15092933abd
Create Date: 2025-11-09 15:24:37.583953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42403d6f648'
down_revision = 'a15092933abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithm_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduling_period_id', sa.Integer(), nullable=False),
    sa.Column('log_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scheduling_period_id'], ['scheduling_period.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('algorithm_log')
    # ### end Alembic commands ###
